routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BaseController;
use App\Http\Controllers\ExcelController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\StoreController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/', [BaseController::class, 'index'])->name('home');
    Route::resource('/product', ProductController::class);

    Route::resource('/store', StoreController::class);
    Route::resource('/review', ReviewController::class);



    Route::get('user/', [BaseController::class, 'users']);
    Route::get('user/{id}', [BaseController::class, 'detail'])->middleware('key');
});
Route::get('/excel', [ExcelController::class, 'index']);
Route::post('/import/user', [ExcelController::class, 'import'])->name('import.user');
Route::get('/export/user', [ExcelController::class, 'export'])->name('export.user');
// Route::get('/stores', [BaseController::class, 'stores']);
// Route::get('/reviews', [BaseController::class, 'reviews']);

// Route::get('user/', [BaseController::class, 'users']);
// Route::get('user/{id}', [BaseController::class, 'users'])->middleware('key');

app/Models/Store.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'user_id'
    ];

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/StoreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Store;
use App\Models\User;
use Exception;
use Illuminate\Http\Request;
use Yajra\DataTables\Contracts\DataTable;
use Yajra\DataTables\Facades\DataTables;

class StoreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stores = Store::all();
        if (request()->ajax()) {
            return DataTables::of($stores)
                ->addIndexColumn()
                ->addColumn('store.owner', function ($item) {
                    return $item->user->name;
                })
                ->addColumn('action', function ($item) {
                    $render = '
                    <a href="' . route('store.edit', $item->id) . '" class="btn btn-success">Edit</a>
                    <a id="delete-store" item-id="' . $item->id . '" class="btn btn-danger btn-delete" >Hapus</a>';

                    return $render;
                })
                ->make(true);
        }
        return view('pages.stores.index', compact('stores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::doesntHave('store')->get();
        if (count($users) > 0) {
            return view('pages.stores.add', compact('users'));
        } else {
            return redirect('/store')->with('fail', 'Semua user sudah memiliki toko');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $request->validate([
                'name' => 'required',
                'user_id' => 'required'
            ]);

            $name = $request->input('name');
            $user_id = $request->input('user_id');

            $store = Store::create([
                'name' => $name,
                'user_id' => $user_id
            ]);

            if ($store) {
                return redirect('/store')->with('success', 'Sukses Menambah Toko');
            } else {
                return redirect('/store')->with('fail', 'Gagal Menambah Toko');
            }
        } catch (Exception $th) {
            return redirect('/store')->with('fail', 'Error Server atau user sudah memiliki toko');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Store  $store
     * @return \Illuminate\Http\Response
     */
    public function show(Store $store)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Store  $store
     * @return \Illuminate\Http\Response
     */
    public function edit(Store $store)
    {
        $users = User::doesntHave('store')->get();
        $store = $store;
        return view('pages.stores.edit', [
            'users' => $users,
            'store' => $store
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Store  $store
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Store $store)
    {
        $request->validate([
            'name' => 'required',
        ]);

        $store->name = $request->input('name');
        $store->user_id = $request->input('user_id') == null ? $store->user_id : $request->input('user_id');

        if ($store->save()) {
            return redirect('/store')->with('success', 'Sukses Mengubah Toko');
        } else {
            return redirect('/store')->with('fail', 'Gagal Mengubah Toko');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Store  $store
     * @return \Illuminate\Http\Response
     */
    public function destroy(Store $store)
    {
        try {
            if (request()->ajax()) {
                $is_deleted = false;
                $msg = $is_deleted ? "Sukses Menghapus Toko" : "Gagal Menghapus Toko";

                return response()->json([
                    'success' => $is_deleted,
                    'msg' => $msg
                ], 200);
            } else {
                if ($store->delete()) {
                    return redirect('/store')->with('success', 'Sukses Menghapus Toko');
                } else {
                    return redirect('/store')->with('fail', 'Gagal Menghapus Toko');
                }
            }
        } catch (Exception $th) {
            return redirect('/store')->with('fail', 'Error Server');
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    public $title;
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($title)
    {
        $this->title = $title;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/stores/add.blade.php
<x-app-layout title="Add Product">
    <x-form action="{{ route('store.store') }}" id="product-form">

        <div class="form-group">
            <label for="name">Nama Toko : </label>
            <input type="text" class="form-control" id="name" value="{{ old('name') }}" name="name">
            @error('name')
                <div class="alert alert-danger" role="alert">
                    Nama wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="user_id">Owned By : </label>
            <select id="user_id" name="user_id">
                @foreach ($users as $user)
                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Add Store</button>
    </x-form>
</x-app-layout>

resources/views/pages/stores/edit.blade.php
<x-app-layout title="Add Product">
    <x-form action="{{ route('store.update', $store->id) }}" id="product-form">
        @method('PUT')
        <div class="form-group">
            <label for="name">Nama Toko : </label>
            <input type="text" class="form-control" id="name" value="{{ $store->name }}" name="name">
            @error('name')
                <div class="alert alert-danger" role="alert">
                    Nama wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="user_id">Owned By : </label>
            <select id="user_id" value="{{ old('') }}" name="user_id">
                @foreach ($users as $user)
                    <option {{ $user->id == $store->user_id ? 'selected' : '' }} value="{{ $user->id }}">
                        {{ $user->name }}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Edit Store</button>
    </x-form>
</x-app-layout>

resources/views/pages/stores/index.blade.php
<x-app-layout title="Stores">
    <div class="content">
        <h1>List of Stores</h1>
    </div>

    <a class="btn btn-primary" href="store/create" role="button">Add Store</a>

    <div class="container">
        <div class="d-flex justify-content-center p-5">
            <table id="table-store" class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nama Toko</th>
                        <th>Nama Pemilik Toko</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>

    @push('scripts')
        <script>
            $(document).ready(function() {
                var datatable;
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                $(function() {
                    datatable = $('#table-store').DataTable({
                        processing: true,
                        serverSide: true,
                        order: [
                            [1, 'desc']
                        ],
                        pageLength: 5,
                        lengthMenu: [2, 10, 50, 100],
                        pagingType: "simple",
                        ajax: "{{ url()->current() }}",
                        columns: [{
                                data: 'DT_RowIndex'
                            },
                            {
                                data: 'name'
                            },
                            {
                                data: 'store.owner'
                            },
                            {
                                data: 'action'
                            },
                        ],
                    });
                });
            });

            $("#table-store").on("click", '.btn-delete', function() {
                var item_id = $(this).attr('item-id');
                $.ajax({
                    type: 'DELETE',
                    url: `{{ route('store.destroy', '') }}/${item_id}`,
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    data: {
                        _token: "{{ csrf_token() }}"
                    },
                    success: function(data) {
                        if (data.success) {
                            alert(data.success);
                            // $("#table-store").DataTable().ajax.reload();
                        } else {
                            alert(data.msg);
                        }
                        console.log(data);
                    }

                })
            });
        </script>
    @endpush

</x-app-layout>