routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BaseController;
use App\Http\Controllers\ExcelController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\StoreController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/', [BaseController::class, 'index'])->name('home');
    Route::resource('/product', ProductController::class);

    Route::resource('/store', StoreController::class);
    Route::resource('/review', ReviewController::class);



    Route::get('user/', [BaseController::class, 'users']);
    Route::get('user/{id}', [BaseController::class, 'detail'])->middleware('key');
});
Route::get('/excel', [ExcelController::class, 'index']);
Route::post('/import/user', [ExcelController::class, 'import'])->name('import.user');
Route::get('/export/user', [ExcelController::class, 'export'])->name('export.user');
// Route::get('/stores', [BaseController::class, 'stores']);
// Route::get('/reviews', [BaseController::class, 'reviews']);

// Route::get('user/', [BaseController::class, 'users']);
// Route::get('user/{id}', [BaseController::class, 'users'])->middleware('key');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;


    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'slug',
        'price',
        'description',
        'photo',
        'store_id',
    ];

    public function reviews()
    {
        return $this->belongsToMany(User::class, 'product_reviews')
            ->using(RoleUser::class);
    }

    public function store()
    {
        return $this->belongsTo(Store::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Store;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect()->action([BaseController::class, 'index']);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $stores = Store::all();
        return view('pages.products.add', compact('stores'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
            'description' => 'required',
            'store' => 'required',
            'photo' => 'required|mimes:png,jpg'
        ]);

        $name = $request->input('name');
        $price = $request->input('price');
        $description = $request->input('description');

        $store_id = $request->input('store');
        $photo = $request->file('photo')->store('uploads');

        $product = Product::create([
            'name' => $name,
            'slug' => Str::slug($name),
            'price' => $price,
            'description' => $description,
            'photo' => $photo,
            'store_id' => $store_id
        ]);




        if ($product) {
            return redirect('/')->with('success', 'Sukses Menambah Produk');
        } else {
            return redirect('/')->with('fail', 'Sukses Menambah Produk');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        // 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $stores = Store::all();
        return view('pages.products.edit', ['product' => $product, 'stores' => $stores]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
            'description' => 'required',
            'store' => 'required',
            'photo' => 'required|mimes:png,jpg'
        ]);

        $product->name = $request->input('name');
        $product->price = $request->input('price');
        $product->description = $request->input('description');
        $product->store_id = $request->input('store');


        if (is_file($product->photo)) {
            // 1. possibility
            Storage::delete($product->photo);
            // 2. possibility
            unlink(storage_path('app/uploads/' . $product->photo));
        }
        $product->photo = $request->file('photo')->store('uploads');
        if ($product->save()) {
            return redirect('/')->with('success', 'Sukses Mengubah Produk');
        } else {
            return redirect('/')->with('fail', 'Gagal Mengubah Produk');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        try {
            if (request()->ajax()) {
                $is_deleted = $product->delete();
                return response()->json([
                    'msg' => $is_deleted
                ], 200);
            } else {
                if ($product->delete()) {
                    return redirect('/')->with('success', 'Sukses Menghapus Produk');
                } else {
                    return redirect('/')->with('fail', 'Gagal Menghapus Produk');
                }
            }
        } catch (Exception $th) {
            return redirect('/')->with('fail', 'Error Server');
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    public $title;
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($title)
    {
        $this->title = $title;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/products/add.blade.php
<x-app-layout title="Add Product">
    <x-form action="{{ route('product.store') }}" id="product-form">

        <div class="form-group">
            <label for="name">Name : </label>
            <input type="text" class="form-control" id="name" value="{{ old('name') }}" name="name">
            @error('name')
                <div class="alert alert-danger" role="alert">
                    Nama wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="product-price">Price : </label>
            <input type="number" class="form-control" id="product-price" value="{{ old('price') }}" name="price">
            @error('price')
                <div class="alert alert-danger" role="alert">
                    Harga wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="description">Description : </label>
            <textarea id="description" class="form-control" name="description" form="product-form">{{ old('description') }}</textarea>
            @error('description')
                <div class="alert alert-danger" role="alert">
                    Deskripsi wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="photo">Upload Photo</label>
            <input type="file" class="form-control-file" id="photo" value="{{ old('') }}" name="photo">
        </div>

        <div class="form-group">
            <label for="store">Store : </label>
            <select id="store" value="{{ old('') }}" name="store">
                @foreach ($stores as $store)
                    <option value="{{ $store->id }}">{{ $store->name }}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Add Product</button>
    </x-form>
    @if ($errors->any())
        <h1>{{ $errors }}</h1>
    @endif
</x-app-layout>

resources/views/pages/products/edit.blade.php
<x-app-layout title="Edit Product">
    <x-form action="{{ route('product.update', $product->id) }}" id="product-form">
        @method('PUT')
        <div class="form-group">
            <label for="name">Name : </label>
            <input type="text" class="form-control" id="name" value="{{ $product->name }}" name="name">
            @error('name')
                <div class="alert alert-danger" role="alert">
                    Nama wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="product-price">Price : </label>
            <input type="number" class="form-control" id="product-price" value="{{ $product->price }}" name="price">
            @error('price')
                <div class="alert alert-danger" role="alert">
                    Harga wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="description">Description : </label>
            <textarea id="description" class="form-control" name="description" form="product-form">{{ $product->description }}</textarea>
            @error('description')
                <div class="alert alert-danger" role="alert">
                    Deskripsi wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="photo">Upload Photo</label>
            <input type="file" class="form-control-file" id="photo" value="{{ $product->photo }}" name="photo">
        </div>

        <div class="form-group">
            <label for="store">Store : </label>
            <select id="store" name="store">
                @foreach ($stores as $store)
                    <option {{ $store->id == $product->store_id ? 'selected' : '' }} value="{{ $store->id }}">
                        {{ $store->name }}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Edit Product</button>

    </x-form>
</x-app-layout>

resources/views/pages/products/index.blade.php
<x-app-layout title="Products">
    <div class="content">
        <h1>List of Products</h1>
    </div>

    <a class="btn btn-primary" href="product/create" role="button">Add Product</a>

    <div class="container">
        <div class="d-flex justify-content-center p-5">
            <table id="table-product" class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Photo</th>
                        <th>Nama Produk</th>
                        <th>Nama Toko</th>
                        <th>Harga Barang</th>
                        <th>Deskripsi Barang</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>



    @push('scripts')
        <script>
            $(document).ready(function() {
                var datatable;
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                $(function() {
                    datatable = $('#table-product').DataTable({
                        processing: true,
                        serverSide: true,
                        order: [
                            [0, 'asc']
                        ],
                        pageLength: 5,
                        lengthMenu: [2, 10, 50, 100],
                        pagingType: "simple",
                        ajax: "{{ url()->current() }}",
                        columns: [{
                                data: 'DT_RowIndex'
                            },
                            {
                                data: 'photo',
                            },
                            {
                                data: 'name'
                            },
                            {
                                data: 'store.name'
                            },
                            {
                                data: 'price'
                            },
                            {
                                data: 'description'
                            },
                            {
                                data: 'action'
                            },
                        ],
                    });
                });


            });

            $("#table-product").on("click", '.btn-delete', function() {
                var item_id = $(this).attr('item-id');
                var test = `{{ route('product.destroy', '') }}/${item_id}`;
                $.ajax({
                    type: 'DELETE',
                    url: `{{ route('product.destroy', '') }}/${item_id}`,
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    data: {
                        _token: "{{ csrf_token() }}"
                    },
                    success: function(data) {
                        console.log(data);
                        $("#table-product").DataTable().ajax.reload();
                    }

                })
            });
        </script>
    @endpush


</x-app-layout>