routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BaseController;
use App\Http\Controllers\ExcelController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\StoreController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/', [BaseController::class, 'index'])->name('home');
    Route::resource('/product', ProductController::class);

    Route::resource('/store', StoreController::class);
    Route::resource('/review', ReviewController::class);



    Route::get('user/', [BaseController::class, 'users']);
    Route::get('user/{id}', [BaseController::class, 'detail'])->middleware('key');
});
Route::get('/excel', [ExcelController::class, 'index']);
Route::post('/import/user', [ExcelController::class, 'import'])->name('import.user');
Route::get('/export/user', [ExcelController::class, 'export'])->name('export.user');
// Route::get('/stores', [BaseController::class, 'stores']);
// Route::get('/reviews', [BaseController::class, 'reviews']);

// Route::get('user/', [BaseController::class, 'users']);
// Route::get('user/{id}', [BaseController::class, 'users'])->middleware('key');

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\ProductReview;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;

class ReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // return dd(auth()->user()->id);
        $reviews = ProductReview::where('user_id', auth()->user()->id)->get();
        // return dd($reviews[0]->product);
        return view('pages.reviews.index', ['reviews' => $reviews]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::find(auth()->user()->id);
        $products = Product::all();
        return view('pages.reviews.add', compact('users', 'products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'score' => 'required',
            'review' => 'required',
            'product_id' => 'required',
            'user_id' => 'required',
        ]);

        $score = $request->input('score');
        $review = $request->input('review');
        $user_id = $request->input('user_id');
        $product_id = $request->input('product_id');

        // return dd("TEST");
        $product = Product::find($product_id);
        $product->reviews()->attach($user_id, [
            'score' => $score,
            'review' => $review
        ]);



        if ($product->save()) {
            return redirect('/review')->with('success', 'Sukses Menambah Komentar');
        } else {
            return redirect('/review')->with('fail', 'Gagal Menambah Komentar');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(ProductReview $review)
    {
        $user = Auth::user();
        return view('pages.reviews.edit', ['review' => $review, 'user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ProductReview $review)
    {
        $request->validate([
            'score' => 'required',
            'review' => 'required',
        ]);

        $review->review = $request->input('review');
        $review->score = $request->input('score');

        if ($review->save()) {
            return redirect('/review')->with('success', 'Sukses Mengubah Review');
        } else {
            return redirect('/review')->with('fail', 'Gagal Mengubah Review');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    public $title;
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($title)
    {
        $this->title = $title;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/reviews/add.blade.php
<x-app-layout title="Add Review">
    <x-form action="{{ route('review.store') }}" id="review-form">

        <div class="form-group">
            <label for="review">Review : </label>
            <input type="text" class="form-control" id="review" value="{{ old('review') }}" name="review">
            @error('review')
                <div class="alert alert-danger" role="alert">
                    Review wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="score">Score : </label>
            <input type="number" class="form-control" id="score" min="0" max="5"
                value="{{ old('name') ? old('name') : 0 }}" name="score">
            @error('score')
                <div class="alert alert-danger" role="alert">
                    score wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="product_id">Product : </label>
            <select id="product_id" name="product_id">
                @foreach ($products as $product)
                    <option value="{{ $product->id }}">{{ $product->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="user_id">Review By : </label>
            <select id="user_id" name="user_id" disabled>
                <option value="{{ $users->id }}">{{ $users->name }}</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Add Review</button>
    </x-form>
</x-app-layout>

resources/views/pages/reviews/edit.blade.php
<x-app-layout title="Add Review">
    <x-form action="{{ route('review.update', $review->id) }}" id="review-form">
        @method('PATCH')
        <div class="form-group">
            <label for="review">Review : </label>
            <input type="text" class="form-control" id="review" value="{{ $review->review }}" name="review">
            @error('review')
                <div class="alert alert-danger" role="alert">
                    Review wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="score">Score : </label>
            <input type="number" class="form-control" id="score" min="0" max="5"
                value="{{ $review->score }}" name="score">
            @error('score')
                <div class="alert alert-danger" role="alert">
                    score wajib diisi
                </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="product_id">Product : </label>
            <select id="product_id" name="product_id" disabled>
                <option value="{{ $review->product->id }}">{{ $review->product->name }}</option>
            </select>
        </div>

        <div class="form-group">
            <label for="user_id">Review By : </label>
            <select id="user_id" name="user_id" disabled>
                <option value="{{ $user->id }}">{{ $user->name }}</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Edit Review</button>
    </x-form>
</x-app-layout>

resources/views/pages/reviews/index.blade.php
<x-app-layout title="Reviews" show_edit="true" show_delet="true">
    <div class="content">
        <h1>List of Product Reviews by {{ Auth::user()->name }}</h1>
    </div>

    <a class="btn btn-primary" href="{{ route('review.create') }}" role="button">Add Review</a>


    @foreach ($reviews as $review)
        <x-card title="Produk : {{ $review->product->name }}" edit="{{ route('review.edit', $review->id) }}"
            delete="{{ route('review.destroy', $review->id) }}" link="#">
            <p class="card-text">
                "{{ $review->review }}", Score : {{ $review->score }}
            </p>
        </x-card>
    @endforeach
</x-app-layout>